spring:
  datasource:
    url: "jdbc:mysql://localhost/library" # using jdbc connect to mysql, location: localhost, database: library
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver # program to connect ro database